### ISSUE TITLE
Error "Failed loading Op reshape0 of type Reshape" at mx.model.load_checkpoint("cnn-ocr",1)

### ISSUE THREAD

**Issue by lushuicongsheng** [xlvector/learning-dl#10]
D:\git\mxnet\example\cnn_ocr>python infer_cnn_ocr.py
gen captcha: 0039
Traceback (most recent call last):
  File "infer_cnn_ocr.py", line 46, in <module>
    _, arg_params, __ = mx.model.load_checkpoint("D:/git/mxnet/example/cnn_ocr/cnn-ocr", 1)
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\model.py", line 363, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.py", line 958, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op reshape0 of type Reshape: Invalid Parameter format for shape expect  but value='()'
Maybe cause by this " label = mx.symbol.Reshape(data = label, target_shape = (0, )) ",how to fix it?

**Comment by lushuicongsheng** [comment]
modify cnn-ocr-symbol.json file，
{
      "op": "Reshape", 
      "param": {
        "keep_highest": "False", 
        "shape": "(1)", 
        "target_shape": "(0,)"
      }, 
      "name": "reshape0", 
      "inputs": [[39, 0]], 
      "backward_source_id": -1
    }
set “shape":"(1)" then it works,but don't know why?

**Comment by xlvector** [comment]
Do you use latest mxnet?

**Comment by lushuicongsheng** [comment]
Seems cause by old version mxnet.
