### ISSUE TITLE
lstm + ctc for ocr?

### ISSUE THREAD

**Issue by anxingle** [xlvector/learning-dl#2]
Sorry to bother you.
 Can you push your lstm_ocr.py in this repository? I really want to know the struct of rnn before you Integrate warpctc in mxnet,so I could rewrite it in tensorflow.

**Comment by anxingle** [comment]
It disturbs me : [mx.sym.WarpCTC](https://github.com/dmlc/mxnet/blob/master/example/warpctc/lstm.py#L77)

**Comment by xlvector** [comment]
https://github.com/dmlc/mxnet/tree/master/example/warpctc

mx.sym.WarpCTC is implemented in https://github.com/dmlc/mxnet/tree/master/plugin/warpctc

**Comment by anxingle** [comment]
Thank you .  [It https://github.com/dmlc/mxnet/tree/master/plugin/warpctc)(https://github.com/dmlc/mxnet/tree/master/plugin/warpctc) help me a lot!

**Comment by xlvector** [comment]
Are you still in CASIA? who is your supervisor?

**Comment by anxingle** [comment]
复杂系统实验室（自动化大厦1023）   王春恒老师
